---
functional:
  - Пользователь должен иметь возможность зарегистрироваться.
  - Пользователь должен иметь возможность зайти на сайт через аккаунты GitHub или Discord
  - Пользователь должен иметь возможность просматривать LEADERBOARD неделя/месяц/общее
  - Пользователь должен иметь возможность создать игру с разными уровнями сложности и характеристиками, и разными соперниками(онлайн/друг/бот)
  - Пользователь должен иметь возможность зайти к себе в "профиль" и возможность переключаться на свою статистику и кол-во завершенных игр
  - Пользовтаель должен иметь возможность зайти к себе в "настроики" и поменять себе ник, сменить оружее(язык пограммирования), настроить тип и громкость звука. выйти в социальные сети
  - Пользовтаель должен иметь возможность посмотреть "рейтинг" игроков и иметь возможность сортировать по разным характеристикам
  - Пользователь должен иметь возможность зайти в "задания" и иметь возможность их смотреть, создавать или удалять
  - Пользователь должен иметь возможность зайти в "Туриниры" и посмотреть которые были или будут, и создавть свой турир
  
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.   
  - Сайт должен быть способен обрабатывать большое количество трафика    
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - (Сайт должен быть доступен на различных устройствах)
  
implicit:
  - 
